# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import minitwitter_pb2 as minitwitter__pb2


class MiniTwitterStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.sendMessage = channel.unary_unary(
                '/MiniTwitter/sendMessage',
                request_serializer=minitwitter__pb2.Message.SerializeToString,
                response_deserializer=minitwitter__pb2.Message.FromString,
                )
        self.getMessages = channel.unary_stream(
                '/MiniTwitter/getMessages',
                request_serializer=minitwitter__pb2.GetMessagesRequest.SerializeToString,
                response_deserializer=minitwitter__pb2.Message.FromString,
                )
        self.getMessagesWithHashtag = channel.unary_stream(
                '/MiniTwitter/getMessagesWithHashtag',
                request_serializer=minitwitter__pb2.GetMessagesWithHashtagRequest.SerializeToString,
                response_deserializer=minitwitter__pb2.Message.FromString,
                )


class MiniTwitterServicer(object):
    """Missing associated documentation comment in .proto file."""

    def sendMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getMessages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getMessagesWithHashtag(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MiniTwitterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'sendMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.sendMessage,
                    request_deserializer=minitwitter__pb2.Message.FromString,
                    response_serializer=minitwitter__pb2.Message.SerializeToString,
            ),
            'getMessages': grpc.unary_stream_rpc_method_handler(
                    servicer.getMessages,
                    request_deserializer=minitwitter__pb2.GetMessagesRequest.FromString,
                    response_serializer=minitwitter__pb2.Message.SerializeToString,
            ),
            'getMessagesWithHashtag': grpc.unary_stream_rpc_method_handler(
                    servicer.getMessagesWithHashtag,
                    request_deserializer=minitwitter__pb2.GetMessagesWithHashtagRequest.FromString,
                    response_serializer=minitwitter__pb2.Message.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'MiniTwitter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MiniTwitter(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def sendMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/MiniTwitter/sendMessage',
            minitwitter__pb2.Message.SerializeToString,
            minitwitter__pb2.Message.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getMessages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/MiniTwitter/getMessages',
            minitwitter__pb2.GetMessagesRequest.SerializeToString,
            minitwitter__pb2.Message.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getMessagesWithHashtag(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/MiniTwitter/getMessagesWithHashtag',
            minitwitter__pb2.GetMessagesWithHashtagRequest.SerializeToString,
            minitwitter__pb2.Message.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
