# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: minitwitter.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11minitwitter.proto\"\x1a\n\x07Message\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\"\x1f\n\x12GetMessagesRequest\x12\t\n\x01n\x18\x01 \x01(\x05\"0\n\x12\x42ulkMessageRequest\x12\x1a\n\x08messages\x18\x01 \x03(\x0b\x32\x08.Message2\x95\x01\n\x0bMiniTwitter\x12!\n\x0bsendMessage\x12\x08.Message\x1a\x08.Message\x12.\n\x0bgetMessages\x12\x13.GetMessagesRequest\x1a\x08.Message0\x01\x12\x33\n\x10sendBulkMessages\x12\x13.BulkMessageRequest\x1a\x08.Message0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'minitwitter_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_MESSAGE']._serialized_start=21
  _globals['_MESSAGE']._serialized_end=47
  _globals['_GETMESSAGESREQUEST']._serialized_start=49
  _globals['_GETMESSAGESREQUEST']._serialized_end=80
  _globals['_BULKMESSAGEREQUEST']._serialized_start=82
  _globals['_BULKMESSAGEREQUEST']._serialized_end=130
  _globals['_MINITWITTER']._serialized_start=133
  _globals['_MINITWITTER']._serialized_end=282
# @@protoc_insertion_point(module_scope)
